@startuml
class Ristorante {
    + nome : string = ""
    + punteggio : int
    + magazzinoIngredienti : List<OggettoQuantita<int>>
    + Ristorante(nome:string, punteggio:int, magazzinoIngredienti:List<OggettoQuantita<int>>)
    + Ristorante()
    + <<override>> Equals(obj:object) : bool
    + <<override>> ToString() : string
    + {static} fillMagazzinoIngredienti() : List<OggettoQuantita<int>>
}
@enduml
