@startuml
class Item {
    + idItem : int
    + nome : string = ""
    + descrizione : string = ""
    + Item(idItem:int, nome:string, descrizione:string)
    + Item(nome:string)
    + Item()
    + <<override>> Equals(obj:object) : bool
    + <<override>> ToString() : string
    + {static} creaNuovoItem(nome:string) : Item
}
@enduml
