@startuml
class Database {
    + {static} Main() : void
    + {static} getDatabaseOggetto(oggetto:Oggetto) : List<Oggetto>
    + {static} getUltimoOggettoAggiuntoAlDatabase(oggetto:Oggetto, databaseOggetto:List<Oggetto>) : Oggetto
    # {static} oggettoGiaPresente(oggetto:Oggetto, databaseOggetto:List<Oggetto>) : bool
    # {static} salvaNuovoOggettoSuFile(oggetto:Oggetto, databaseOggetto:List<Oggetto>) : void
    + {static} getNewId(oggetto:Oggetto) : int
    + {static} getNewStringaFromUtente(output:string) : string
    + {static} getNewIntFromUtente(output:string) : int
    # {static} getNewFloatFromUtente(output:string) : float
    - {static} creaDatabase() : void
    - {static} pulisciDatabase() : void
    - {static} creaDatabaseVuoto() : void
    - {static} creaDatabaseVuotoCliente() : void
    - {static} creaDatabaseVuotoDieta() : void
    - {static} creaDatabaseVuotoIngrediente() : void
    - {static} creaDatabaseVuotoItem() : void
    - {static} creaDatabaseVuotoPatologia() : void
    - {static} creaDatabaseVuotoPiatto() : void
    - {static} creaDatabaseVuotoPlayer() : void
    - {static} creaDatabaseVuotoRistorante() : void
    - {static} aggiungiRistorante(ristorante:Ristorante) : void
    - {static} aggiungiPlayer(player:Player) : void
    - {static} aggiungiPiatto(piatto:Piatto) : void
    - {static} aggiungiPatologia(patologia:Patologia) : void
    + {static} aggiungiIngrediente(ingrediente:Ingrediente) : void
    - {static} aggiungiDieta(dieta:Dieta) : void
    - {static} aggiungiCliente(cliente:Cliente) : void
}
@enduml
