@startuml
class Ingrediente {
    + costo : float = 0
    + costoEco : int = 0
    + nutriScore : int = 0
    + dieta : int
    + Ingrediente(idItem:int, nome:string, descrizione:string, costo:float, costoEco:int, nutriScore:int, dieta:int, listaIdPatologieCompatibili:List <int>)
    + Ingrediente()
    + Ingrediente(nomeIngrediente:string)
    + {static} checkIngredienteOnonimoGiaPresente(nomeIngrediente:string) : Ingrediente
    + {static} getIngredientiConNomeSimileInDatabase(nomeIngrediente:string, databaseIngredienti:List<Ingrediente>) : List <Ingrediente>
    + {static} scegliIngredienteConNomeSimile(nomeIngrediente:string, ingredientiConNomeSimile:List <Ingrediente>) : Ingrediente
    - {static} stampaIngredientiSimiliPerSceltaUtente(nomeIngrediente:string, ingredientiConNomeSimile:List <Ingrediente>) : void
    + getNewNumeroIngredienteFromUtente(output:string, outputError:string) : float
    + {static} IdToIngrediente(id:int) : Ingrediente
}
class "List`1"<T> {
}
Item <|-- Ingrediente
Ingrediente o-> "listaIdPatologieCompatibili<int>" "List`1"
@enduml
