@startuml
class Player {
    + nome : string = ""
    + soldi : float = 0
    + Player(nome:string, soldi:int, inventario:List<OggettoQuantita<int>>)
    + Player()
    + {static} popolaInventario(itemGiaPresenti:List <Item>) : List<OggettoQuantita<int>>
    - {static} getNewItem(itemGiaPresenti:List <Item>) : List <Item>
    - {static} chiediQuantitaItem(itemGiaPresenti:List <Item>) : List <int>
    - {static} creaInventarioFromListaItemEQuantita(itemGiaPresenti:List <Item>, quantitaItemGiaPresenti:List <int>) : List<OggettoQuantita<int>>
}
class "List`1"<T> {
}
Player o-> "inventario<OggettoQuantita<int>>" "List`1"
@enduml
